<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "powermail_exportperms"
 *
 * Auto generated by Extension Builder 2014-10-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Powermail Export Permissions',
    'description' => 'Grants value to read or export submitted Powermail mails only to editors that have write access to the current page.',
    'category' => 'be',
    'author' => 'Lorenz Ulrich',
    'author_email' => 'lorenz.ulrich@visol.ch',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.99.99',
            'powermail' => '5.3.0-',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
