<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "powermail_exportperms"
 *
 * Auto generated by Extension Builder 2014-10-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Powermail Export Permissions',
	'description' => 'Grants value to read or export submitted Powermail mails only to editors that have write access to the current page.',
	'category' => 'be',
	'author' => 'Lorenz Ulrich',
	'author_email' => 'lorenz.ulrich@visol.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'powermail' => '2.1.0-3.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);